services:
  label-studio:
    image: heartexlabs/label-studio:latest
    platform: linux/amd64
    container_name: labelstudio
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/data
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    restart: always

  yolo-ml-backend:
    image: heartexlabs/label-studio-ml-backend:latest
    platform: linux/amd64
    environment:
      - LABEL_STUDIO_URL=http://label-studio:8080
      - LABEL_STUDIO_API_KEY=${LABEL_STUDIO_API_KEY}
    ports:
      - "9090:9090"
    depends_on:
      - label-studio
    restart: always
